<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class ShopKartSeeder extends Seeder
{
    public function run(): void
    {
        // 1. Create Admin & Customer Users
        User::updateOrCreate(
            ['email' => 'karthikm45@gmail.com'],
            [
                'name' => 'Karthikeyan (Admin)',
                'password' => Hash::make('karthi45'),
                'role' => 'admin',
            ]
        );

        User::updateOrCreate(
            ['email' => 'admin@shopkart.com'],
            [
                'name' => 'ShopKart Admin',
                'password' => Hash::make('password123'),
                'role' => 'admin',
            ]
        );

        User::updateOrCreate(
            ['email' => 'user@shopkart.com'],
            [
                'name' => 'Alex Morgan',
                'password' => Hash::make('password123'),
                'role' => 'user',
            ]
        );

        // 2. Categories Data (8 Categories)
        $categoriesData = [
            [
                'name' => 'Electronics',
                'slug' => 'electronics',
                'description' => 'Latest gadgets, smartphones, wireless headphones, and smart home tech.',
            ],
            [
                'name' => 'Fashion & Wearables',
                'slug' => 'fashion',
                'description' => 'Trendy streetwear, jackets, hoodies, denim, and apparel.',
            ],
            [
                'name' => 'Gaming & Accessories',
                'slug' => 'gaming',
                'description' => 'Mechanical keyboards, gaming mice, headsets, controllers, and gear.',
            ],
            [
                'name' => 'Home & Lifestyle',
                'slug' => 'home-lifestyle',
                'description' => 'Smart desk lamps, ultrasonic diffusers, purifiers, and decor.',
            ],
            [
                'name' => 'Premium Footwear',
                'slug' => 'footwear',
                'description' => 'Running sneakers, leather shoes, boots, and casual slides.',
            ],
            [
                'name' => 'Beauty & Wellness',
                'slug' => 'beauty-wellness',
                'description' => 'Skincare serums, grooming trimmers, hair care, and wellness tools.',
            ],
            [
                'name' => 'Sports & Fitness',
                'slug' => 'sports-fitness',
                'description' => 'Dumbbells, yoga mats, resistance bands, and fitness accessories.',
            ],
            [
                'name' => 'Toys & Hobbies',
                'slug' => 'toys-hobbies',
                'description' => 'STEM kits, RC cars, telescopes, art supplies, and board games.',
            ],
        ];

        $categories = [];
        foreach ($categoriesData as $cat) {
            $categories[$cat['slug']] = Category::updateOrCreate(
                ['slug' => $cat['slug']],
                $cat
            );
        }

        // 3. Products Data (20 Products per Category = 160 Products)
        $productsData = [
            // ELECTRONICS (20 Products)
            [
                'category_slug' => 'electronics',
                'name' => 'SonicBlast Pro Wireless Headphones',
                'slug' => 'sonicblast-pro-wireless-headphones',
                'description' => 'Industry-leading noise cancellation, 40-hour battery life, spatial audio processing, and ultra-soft memory foam cushions.',
                'price' => 12999.00,
                'stock' => 45,
                'sku' => 'SKU-ELEC-001',
                'image_url' => 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'AeroWatch Ultra Smartwatch',
                'slug' => 'aerowatch-ultra-smartwatch',
                'description' => 'Retina AMOLED display, ECG monitor, SpO2 sensor, dual-frequency GPS, and 50m water resistance rating.',
                'price' => 18499.00,
                'stock' => 30,
                'sku' => 'SKU-ELEC-002',
                'image_url' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'ClearTone ANC Wireless Earbuds',
                'slug' => 'cleartone-anc-wireless-earbuds',
                'description' => 'Active noise cancelling Bluetooth 5.3 earbuds with Qi wireless charging case and IPX7 sweatproof design.',
                'price' => 4999.00,
                'stock' => 60,
                'sku' => 'SKU-ELEC-003',
                'image_url' => 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'VisionX 4K Ultra HD Action Camera',
                'slug' => 'visionx-4k-ultra-hd-action-camera',
                'description' => '4K 60FPS video recording, 6-axis electronic image stabilization, waterproof up to 30 meters.',
                'price' => 11499.00,
                'stock' => 25,
                'sku' => 'SKU-ELEC-004',
                'image_url' => 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'PowerBank Pro 20000mAh Fast Charger',
                'slug' => 'powerbank-pro-20000mah-fast-charger',
                'description' => '65W Power Delivery fast charging powerbank for laptops, smartphones, and tablets.',
                'price' => 3299.00,
                'stock' => 80,
                'sku' => 'SKU-ELEC-005',
                'image_url' => 'https://images.unsplash.com/photo-1609592424009-54157a552e69?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'SoundTower 100W Bluetooth Speaker',
                'slug' => 'soundtower-100w-bluetooth-speaker',
                'description' => 'Deep bass radiator, party light sync modes, 24-hour continuous playback time.',
                'price' => 8999.00,
                'stock' => 35,
                'sku' => 'SKU-ELEC-006',
                'image_url' => 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'UltraSlim 8-in-1 USB-C Hub Adapter',
                'slug' => 'ultraslim-8in1-usbc-hub-adapter',
                'description' => 'HDMI 4K 60Hz, 100W PD charging, SD card reader, ethernet gigabit port, aluminum body.',
                'price' => 2799.00,
                'stock' => 90,
                'sku' => 'SKU-ELEC-007',
                'image_url' => 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'SmartSight Home Security Wi-Fi Camera',
                'slug' => 'smartsight-home-security-wifi-camera',
                'description' => '2K resolution, 360-degree motion tracking, night vision, two-way audio communication.',
                'price' => 2499.00,
                'stock' => 50,
                'sku' => 'SKU-ELEC-008',
                'image_url' => 'https://images.unsplash.com/photo-1557324232-b8917d3c3dcb?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'CrystalView 27-inch 4K IPS Monitor',
                'slug' => 'crystalview-27inch-4k-ips-monitor',
                'description' => 'HDR400, 99% sRGB color gamut, USB-C 65W power delivery, ergonomic tilt & swivel stand.',
                'price' => 27999.00,
                'stock' => 20,
                'sku' => 'SKU-ELEC-009',
                'image_url' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'SonicBeam Wireless Soundbar with Subwoofer',
                'slug' => 'sonicbeam-wireless-soundbar-subwoofer',
                'description' => 'Dolby Atmos surround sound, wireless subwoofer, HDMI eARC, optical and Bluetooth connectivity.',
                'price' => 14999.00,
                'stock' => 22,
                'sku' => 'SKU-ELEC-010',
                'image_url' => 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'AeroTab Pro 11-inch Android Tablet',
                'slug' => 'aerotab-pro-11inch-android-tablet',
                'description' => '2.5K 120Hz display, Snapdragon processor, quad speakers, quad-microphone array.',
                'price' => 21999.00,
                'stock' => 28,
                'sku' => 'SKU-ELEC-011',
                'image_url' => 'https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'PocketBeam Portable Mini Projector',
                'slug' => 'pocketbeam-portable-mini-projector',
                'description' => 'Native 1080P resolution, built-in Android OS, Wi-Fi 6, 200 ANSI Lumens brightness.',
                'price' => 9999.00,
                'stock' => 40,
                'sku' => 'SKU-ELEC-012',
                'image_url' => 'https://images.unsplash.com/photo-1535016120720-40c646be5580?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'OmniCharge 3-in-1 Wireless Charging Stand',
                'slug' => 'omnicharge-3in1-wireless-charging-stand',
                'description' => 'Fast MagSafe charging for smartphone, smartwatch, and wireless earbuds simultaneously.',
                'price' => 3499.00,
                'stock' => 70,
                'sku' => 'SKU-ELEC-013',
                'image_url' => 'https://images.unsplash.com/photo-1622445268465-843d6358745f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'ClearMic USB Studio Microphone',
                'slug' => 'clearmic-usb-studio-microphone',
                'description' => 'Cardioid polar pattern, zero-latency headphone monitoring, gain control dial and mute button.',
                'price' => 5499.00,
                'stock' => 45,
                'sku' => 'SKU-ELEC-014',
                'image_url' => 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'WaveSound Studio Monitor Headphones',
                'slug' => 'wavesound-studio-monitor-headphones',
                'description' => '50mm neodymium drivers, accurate sound signature, detachable oxygen-free copper cables.',
                'price' => 6999.00,
                'stock' => 35,
                'sku' => 'SKU-ELEC-015',
                'image_url' => 'https://images.unsplash.com/photo-1484704849700-f032a568e944?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'SmartKey Digital Fingerprint Door Lock',
                'slug' => 'smartkey-digital-fingerprint-door-lock',
                'description' => 'Biometric fingerprint scanner, mobile app control, passcode keypad and emergency physical key.',
                'price' => 8499.00,
                'stock' => 30,
                'sku' => 'SKU-ELEC-016',
                'image_url' => 'https://images.unsplash.com/photo-1558002038-1055907df827?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'AeroDrone Foldable 4K Camera Drone',
                'slug' => 'aerodrone-foldable-4k-camera-drone',
                'description' => 'GPS auto-return, 30-minute flight time per battery, optical flow positioning, 3-axis gimbal.',
                'price' => 19999.00,
                'stock' => 18,
                'sku' => 'SKU-ELEC-017',
                'image_url' => 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'PowerGrid 6-Socket Surge Protector',
                'slug' => 'powergrid-6socket-surge-protector',
                'description' => '2500W heavy duty extension cord with 4 USB charging ports and overload protection switch.',
                'price' => 1499.00,
                'stock' => 100,
                'sku' => 'SKU-ELEC-018',
                'image_url' => 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'VisionVR 3D Virtual Reality Headset',
                'slug' => 'visionvr-3d-virtual-reality-headset',
                'description' => 'Ultra-wide field of view lenses, breathable face padding, universal smartphone holder.',
                'price' => 3999.00,
                'stock' => 50,
                'sku' => 'SKU-ELEC-019',
                'image_url' => 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1bd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'electronics',
                'name' => 'SonicBass Car Bluetooth Audio Receiver',
                'slug' => 'sonicbass-car-bluetooth-audio-receiver',
                'description' => 'AUX 3.5mm Bluetooth 5.3 adapter, built-in noise cancelling handsfree microphone.',
                'price' => 999.00,
                'stock' => 120,
                'sku' => 'SKU-ELEC-020',
                'image_url' => 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
            ],

            // FASHION & WEARABLES (20 Products)
            [
                'category_slug' => 'fashion',
                'name' => 'Urban Luxe Oversized Cotton Hoodie',
                'slug' => 'urban-luxe-oversized-cotton-hoodie',
                'description' => '450 GSM heavyweight organic french terry cotton, relaxed drop-shoulder silhouette, double-lined hood.',
                'price' => 2999.00,
                'stock' => 80,
                'sku' => 'SKU-FASH-001',
                'image_url' => 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Vintage Denim Trucker Jacket',
                'slug' => 'vintage-denim-trucker-jacket',
                'description' => '100% premium cotton rigid denim, washed finish, metal shank buttons, chest flap pockets.',
                'price' => 3499.00,
                'stock' => 50,
                'sku' => 'SKU-FASH-002',
                'image_url' => 'https://images.unsplash.com/photo-1576995853123-5a10305d93c0?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Classic Fit Oxford Cotton Shirt',
                'slug' => 'classic-fit-oxford-cotton-shirt',
                'description' => 'Button-down collar, breathable pure oxford weave cotton, tailored hemline for business or casual wear.',
                'price' => 1999.00,
                'stock' => 65,
                'sku' => 'SKU-FASH-003',
                'image_url' => 'https://images.unsplash.com/photo-1596755094514-f87e34085b2c?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Executive Slim Fit Wool Blazer',
                'slug' => 'executive-slim-fit-wool-blazer',
                'description' => 'Italian wool blend fabric, notch lapels, structured shoulder padding, internal pocket lining.',
                'price' => 6999.00,
                'stock' => 30,
                'sku' => 'SKU-FASH-004',
                'image_url' => 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Streetwear Cargo Jogger Pants',
                'slug' => 'streetwear-cargo-jogger-pants',
                'description' => 'Stretch twill cotton construction, deep utility side cargo pockets, elastic drawstring waist.',
                'price' => 2499.00,
                'stock' => 75,
                'sku' => 'SKU-FASH-005',
                'image_url' => 'https://images.unsplash.com/photo-1624378439575-d8705ad7ae80?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Soft Touch Cashmere Blend Sweater',
                'slug' => 'soft-touch-cashmere-blend-sweater',
                'description' => 'Ultra-fine knit crewneck sweater, lightweight insulation, ribbed cuffs and bottom hem.',
                'price' => 3999.00,
                'stock' => 40,
                'sku' => 'SKU-FASH-006',
                'image_url' => 'https://images.unsplash.com/photo-1620799140408-edc6dcb6d633?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Essential Heavyweight Crewneck T-Shirt',
                'slug' => 'essential-heavyweight-crewneck-tshirt',
                'description' => '240 GSM combed ring-spun cotton, pre-shrunk fabric, reinforced neck tape for longevity.',
                'price' => 999.00,
                'stock' => 120,
                'sku' => 'SKU-FASH-007',
                'image_url' => 'https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Waterproof Outdoor Windbreaker Jacket',
                'slug' => 'waterproof-outdoor-windbreaker-jacket',
                'description' => 'DWR water repellent coating, breathable mesh lining, adjustable storm hood and zippered pockets.',
                'price' => 3299.00,
                'stock' => 45,
                'sku' => 'SKU-FASH-008',
                'image_url' => 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Premium Faux Leather Biker Jacket',
                'slug' => 'premium-faux-leather-biker-jacket',
                'description' => 'Asymmetrical front zip closure, quilted shoulder panels, zippered cuffs, viscose interior lining.',
                'price' => 4999.00,
                'stock' => 35,
                'sku' => 'SKU-FASH-009',
                'image_url' => 'https://images.unsplash.com/photo-1551028719-00167b16eac5?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Athletic Performance Gym T-Shirt',
                'slug' => 'athletic-performance-gym-tshirt',
                'description' => 'Moisture-wicking quick-dry fabric, 4-way stretch material, ergonomic flatlock stitching.',
                'price' => 1199.00,
                'stock' => 95,
                'sku' => 'SKU-FASH-010',
                'image_url' => 'https://images.unsplash.com/photo-1581655353564-df123a1eb820?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Tailored Linen Blend Casual Trousers',
                'slug' => 'tailored-linen-blend-casual-trousers',
                'description' => 'Cooling linen-cotton blend, relaxed straight leg fit, slant front pockets and button rear pockets.',
                'price' => 2799.00,
                'stock' => 50,
                'sku' => 'SKU-FASH-011',
                'image_url' => 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Fleece Tracksuit Hooded 2-Piece Set',
                'slug' => 'fleece-tracksuit-hooded-2piece-set',
                'description' => 'Warm fleece lining, pullover hoodie with kangaroo pocket and matching tapered sweatpants.',
                'price' => 3999.00,
                'stock' => 40,
                'sku' => 'SKU-FASH-012',
                'image_url' => 'https://images.unsplash.com/photo-1556905055-8f358a7a47b2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Heritage Checkered Flannel Shirt',
                'slug' => 'heritage-checkered-flannel-shirt',
                'description' => 'Brushed cotton flannel fabric, twin chest button flap pockets, relaxed casual fit.',
                'price' => 1899.00,
                'stock' => 60,
                'sku' => 'SKU-FASH-013',
                'image_url' => 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Chic Knit Ribbed Turtleneck Sweater',
                'slug' => 'chic-knit-ribbed-turtleneck-sweater',
                'description' => 'High-neck folded collar, stretch ribbed texture, warm acrylic-wool blended yarn.',
                'price' => 2499.00,
                'stock' => 45,
                'sku' => 'SKU-FASH-014',
                'image_url' => 'https://images.unsplash.com/photo-1574201635302-388dd92a4c3f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Modern Fit Double-Breasted Trench Coat',
                'slug' => 'modern-fit-doublebreasted-trench-coat',
                'description' => 'Water resistant twill cloth, belted waist, button epaulets, classic back vent.',
                'price' => 7999.00,
                'stock' => 25,
                'sku' => 'SKU-FASH-015',
                'image_url' => 'https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Organic Pique Cotton Polo Shirt',
                'slug' => 'organic-pique-cotton-polo-shirt',
                'description' => 'Ribbed collar and sleeve cuffs, 2-button placket, embroidered chest crest accent.',
                'price' => 1499.00,
                'stock' => 80,
                'sku' => 'SKU-FASH-016',
                'image_url' => 'https://images.unsplash.com/photo-1586363104862-3a5e2ab60d99?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Graphic Printed Vintage Oversized Tee',
                'slug' => 'graphic-printed-vintage-oversized-tee',
                'description' => 'Acid wash finish, drop shoulder cut, retro screen-printed front artwork.',
                'price' => 1299.00,
                'stock' => 85,
                'sku' => 'SKU-FASH-017',
                'image_url' => 'https://images.unsplash.com/photo-1503342217505-b0a15ec3261c?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Insulated Puffer Winter Vest',
                'slug' => 'insulated-puffer-winter-vest',
                'description' => 'Sleeveless thermal fill vest, stand collar, fleece-lined hand pockets.',
                'price' => 2999.00,
                'stock' => 40,
                'sku' => 'SKU-FASH-018',
                'image_url' => 'https://images.unsplash.com/photo-1548883354-7622d03aca27?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Relaxed Fit Stretch Chino Shorts',
                'slug' => 'relaxed-fit-stretch-chino-shorts',
                'description' => '9-inch inseam, comfortable elastane cotton blend, front slant and rear welt pockets.',
                'price' => 1699.00,
                'stock' => 70,
                'sku' => 'SKU-FASH-019',
                'image_url' => 'https://images.unsplash.com/photo-1591195853828-11db59a44f6b?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'fashion',
                'name' => 'Silk Blend Printed Resort Shirt',
                'slug' => 'silk-blend-printed-resort-shirt',
                'description' => 'Camp collar Cuban style shirt, silky smooth breathable rayon fabric, tropical print.',
                'price' => 2199.00,
                'stock' => 55,
                'sku' => 'SKU-FASH-020',
                'image_url' => 'https://images.unsplash.com/photo-1602810318383-e386cc2a3ccf?auto=format&fit=crop&w=800&q=80',
            ],

            // GAMING & ACCESSORIES (20 Products)
            [
                'category_slug' => 'gaming',
                'name' => 'CyberTactile RGB Mechanical Keyboard',
                'slug' => 'cybertactile-rgb-mechanical-keyboard',
                'description' => 'Hot-swappable tactile switches, aircraft-grade aluminum frame, customizable per-key RGB lighting.',
                'price' => 7999.00,
                'stock' => 60,
                'sku' => 'SKU-GAME-001',
                'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'Vortex 26000 DPI Ergonomic Gaming Mouse',
                'slug' => 'vortex-26000-dpi-gaming-mouse',
                'description' => 'Ultra-lightweight 58g honeycomb shell, optical switches rated for 80M clicks, 1ms wireless response time.',
                'price' => 4499.00,
                'stock' => 25,
                'sku' => 'SKU-GAME-002',
                'image_url' => 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'TitanDesk XXL Extended RGB Mousepad',
                'slug' => 'titandesk-xxl-extended-rgb-mousepad',
                'description' => '900x400mm micro-textured cloth surface, 14 RGB lighting modes, non-slip rubber base.',
                'price' => 1799.00,
                'stock' => 85,
                'sku' => 'SKU-GAME-003',
                'image_url' => 'https://images.unsplash.com/photo-1629429408209-1f912961dbd8?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'Apex360 Wireless Gamepad Controller',
                'slug' => 'apex360-wireless-gamepad-controller',
                'description' => 'Hall effect anti-drift analog sticks, programmable rear paddles, dual rumble motors.',
                'price' => 3999.00,
                'stock' => 50,
                'sku' => 'SKU-GAME-004',
                'image_url' => 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'HyperAudio 7.1 Surround Gaming Headset',
                'slug' => 'hyperaudio-71-surround-gaming-headset',
                'description' => '50mm drivers, detachable noise cancelling mic, memory foam cooling gel ear cushions.',
                'price' => 5499.00,
                'stock' => 40,
                'sku' => 'SKU-GAME-005',
                'image_url' => 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'TitanThrone Ergonomic Gaming Chair',
                'slug' => 'titanthrone-ergonomic-gaming-chair',
                'description' => '4D armrests, magnetic memory foam head pillow, 165-degree recline mechanism, steel frame.',
                'price' => 17999.00,
                'stock' => 15,
                'sku' => 'SKU-GAME-006',
                'image_url' => 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'StreamPro Full HD Webcam with Ring Light',
                'slug' => 'streampro-full-hd-webcam-ring-light',
                'description' => '1080P 60FPS streaming webcam, touch adjustable ring light, autofocus glass lens.',
                'price' => 4999.00,
                'stock' => 35,
                'sku' => 'SKU-GAME-007',
                'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'CyberCool RGB Dual-Fan Laptop Cooling Pad',
                'slug' => 'cybercool-rgb-dualfan-laptop-cooling-pad',
                'description' => 'Fits up to 17.3-inch gaming laptops, 6 quiet fan speed levels, dual USB passthrough ports.',
                'price' => 2299.00,
                'stock' => 60,
                'sku' => 'SKU-GAME-008',
                'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'Nexus Pro Dual Controller Charging Dock',
                'slug' => 'nexus-pro-dual-controller-charging-dock',
                'description' => 'Fast LED status charging station for PS5 and Xbox wireless controllers.',
                'price' => 1699.00,
                'stock' => 75,
                'sku' => 'SKU-GAME-009',
                'image_url' => 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'ApexVoice Cardioid Boom Arm Mic Kit',
                'slug' => 'apexvoice-cardioid-boom-arm-mic-kit',
                'description' => 'Condenser podcast microphone with heavy duty boom arm stand, shock mount and pop filter.',
                'price' => 6499.00,
                'stock' => 30,
                'sku' => 'SKU-GAME-010',
                'image_url' => 'https://images.unsplash.com/photo-1590602847861-f357a9332bbc?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'BattleRig Desktop Cable Management Tray',
                'slug' => 'battlerig-desktop-cable-management-tray',
                'description' => 'Under desk steel wire tray organizer for power strips and gaming rig cables.',
                'price' => 1299.00,
                'stock' => 100,
                'sku' => 'SKU-GAME-011',
                'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'UltraGrip Controller Silicone Covers Set',
                'slug' => 'ultragrip-controller-silicone-covers-set',
                'description' => 'Anti-slip sweatproof controller skin with 8 analog thumb stick grip caps.',
                'price' => 799.00,
                'stock' => 150,
                'sku' => 'SKU-GAME-012',
                'image_url' => 'https://images.unsplash.com/photo-1600080972464-8e5f35f63d08?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'CyberDesk Motorized Height Adjustable Desk',
                'slug' => 'cyberdesk-motorized-height-adjustable-desk',
                'description' => 'Dual motor 140x70cm carbon fiber textured top, preset memory height control buttons.',
                'price' => 24999.00,
                'stock' => 10,
                'sku' => 'SKU-GAME-013',
                'image_url' => 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'Vortex RGB Headset Stand with USB Hub',
                'slug' => 'vortex-rgb-headset-stand-usb-hub',
                'description' => 'Solid aluminum headset hanger with dynamic RGB base lighting and 2 USB ports.',
                'price' => 1999.00,
                'stock' => 65,
                'sku' => 'SKU-GAME-014',
                'image_url' => 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'TitanShield Blue Light Gaming Glasses',
                'slug' => 'titanshield-blue-light-gaming-glasses',
                'description' => 'Anti-eyestrain UV protection yellow tinted lenses with lightweight titanium frame.',
                'price' => 1499.00,
                'stock' => 80,
                'sku' => 'SKU-GAME-015',
                'image_url' => 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'HyperGrip PBT Keycap Set 108 Keys',
                'slug' => 'hypergrip-pbt-keycap-set-108keys',
                'description' => 'Double-shot shine-through PBT keycaps with OEM profile for mechanical keyboards.',
                'price' => 1899.00,
                'stock' => 70,
                'sku' => 'SKU-GAME-016',
                'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'ApexStream 4K60 Ultra HDMI Capture Card',
                'slug' => 'apexstream-4k60-ultra-hdmi-capture-card',
                'description' => 'Low latency USB 3.0 game capture for streaming console gameplay on OBS Twitch.',
                'price' => 8999.00,
                'stock' => 25,
                'sku' => 'SKU-GAME-017',
                'image_url' => 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'GameSphere Virtual Reality Motion Grips',
                'slug' => 'gamesphere-virtual-reality-motion-grips',
                'description' => 'Haptic feedback controllers with active tracking sensors for PC VR gaming.',
                'price' => 12999.00,
                'stock' => 15,
                'sku' => 'SKU-GAME-018',
                'image_url' => 'https://images.unsplash.com/photo-1622979135225-d2ba269bc1bd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'CyberSound 2.1 RGB Desktop Gaming Speakers',
                'slug' => 'cybersound-21-rgb-desktop-gaming-speakers',
                'description' => 'Dedicated wooden subwoofer, Bluetooth 5.0 and AUX mode with reactive bass lighting.',
                'price' => 4799.00,
                'stock' => 45,
                'sku' => 'SKU-GAME-019',
                'image_url' => 'https://images.unsplash.com/photo-1545454675-3531b543be5d?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'gaming',
                'name' => 'TitanMount Heavy Duty Single Monitor Arm',
                'slug' => 'titanmount-heavy-duty-single-monitor-arm',
                'description' => 'Gas spring desk mount for 17 to 32-inch monitors up to 9kg with cable routing.',
                'price' => 2999.00,
                'stock' => 55,
                'sku' => 'SKU-GAME-020',
                'image_url' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
            ],

            // HOME & LIFESTYLE (20 Products)
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'Lumina Smart RGB Desk Lamp',
                'slug' => 'lumina-smart-rgb-desk-lamp',
                'description' => 'Touch control, stepless dimming, smartphone app support, built-in 15W Qi fast wireless charger.',
                'price' => 3499.00,
                'stock' => 50,
                'sku' => 'SKU-HOME-001',
                'image_url' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'AromaPulse Ultrasonic Diffuser',
                'slug' => 'aromapulse-ultrasonic-diffuser',
                'description' => 'Whisper-quiet ceramic essential oil diffuser with ambient warm candle LED light mode.',
                'price' => 2199.00,
                'stock' => 75,
                'sku' => 'SKU-HOME-002',
                'image_url' => 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'AquaPure Smart Temp Water Bottle 600ml',
                'slug' => 'aquapure-smart-temp-water-bottle-600ml',
                'description' => 'LED touch temperature display, double-wall vacuum insulated stainless steel keeps hot 12h cold 24h.',
                'price' => 1499.00,
                'stock' => 90,
                'sku' => 'SKU-HOME-003',
                'image_url' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'ErgoComfort Memory Foam Seat Cushion',
                'slug' => 'ergocomfort-memory-foam-seat-cushion',
                'description' => 'Coccyx tailbone pressure relief cushion for office chairs and car driver seats.',
                'price' => 1799.00,
                'stock' => 60,
                'sku' => 'SKU-HOME-004',
                'image_url' => 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'EcoBamboo 24-Piece Flatware Cutlery Set',
                'slug' => 'ecobamboo-24piece-flatware-cutlery-set',
                'description' => 'Food-grade stainless steel with natural bamboo handles, includes forks, knives, spoons.',
                'price' => 2499.00,
                'stock' => 40,
                'sku' => 'SKU-HOME-005',
                'image_url' => 'https://images.unsplash.com/photo-1615865417491-9556867d5cc1?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'SmartGlow App-Controlled LED Light Strip',
                'slug' => 'smartglow-appcontrolled-led-light-strip',
                'description' => '10-meter RGBIC light strip, music rhythm sync, compatible with Alexa & Google Assistant.',
                'price' => 1999.00,
                'stock' => 85,
                'sku' => 'SKU-HOME-006',
                'image_url' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'VelvetTouch Luxury Throw Blanket',
                'slug' => 'velvettouch-luxury-throw-blanket',
                'description' => 'Ultra-soft microfiber sherpa fleece blanket for couch, bed, and cozy living rooms.',
                'price' => 1899.00,
                'stock' => 50,
                'sku' => 'SKU-HOME-007',
                'image_url' => 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'Ceramic Minimalist Geometric Flower Vase',
                'slug' => 'ceramic-minimalist-geometric-flower-vase',
                'description' => 'Handmade matte white ceramic vase for dried flowers, pampas grass and modern decor.',
                'price' => 1299.00,
                'stock' => 70,
                'sku' => 'SKU-HOME-008',
                'image_url' => 'https://images.unsplash.com/photo-1581783342308-f792dbdd27c5?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'ChefPro 10-Inch Cast Iron Skillet Pan',
                'slug' => 'chefpro-10inch-cast-iron-skillet-pan',
                'description' => 'Pre-seasoned heavy duty cast iron skillet for stovetop, oven, and induction cooking.',
                'price' => 2199.00,
                'stock' => 45,
                'sku' => 'SKU-HOME-009',
                'image_url' => 'https://images.unsplash.com/photo-1584992236310-6edddc08acff?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'AirFresh True HEPA Room Air Purifier',
                'slug' => 'airfresh-true-hepa-room-air-purifier',
                'description' => '3-stage filtration removes 99.97% dust, pollen, pet dander and odors, quiet night mode.',
                'price' => 7999.00,
                'stock' => 30,
                'sku' => 'SKU-HOME-010',
                'image_url' => 'https://images.unsplash.com/photo-1585771724684-38269d6639fd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'HydroMist Automatic Soap Dispenser',
                'slug' => 'hydromist-automatic-soap-dispenser',
                'description' => 'Touchless infrared motion sensor liquid foaming dispenser, USB rechargeable battery.',
                'price' => 1399.00,
                'stock' => 95,
                'sku' => 'SKU-HOME-011',
                'image_url' => 'https://images.unsplash.com/photo-1608571423902-eed4a5ad8108?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'Nordic Solid Wood Silent Wall Clock 12-Inch',
                'slug' => 'nordic-solid-wood-silent-wall-clock-12inch',
                'description' => 'Natural oak wood frame, silent quartz non-ticking mechanism, modern minimalist numerals.',
                'price' => 1699.00,
                'stock' => 60,
                'sku' => 'SKU-HOME-012',
                'image_url' => 'https://images.unsplash.com/photo-1563861826100-9cb868fdbe1c?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'ZenGarden Indoor Tabletop Water Fountain',
                'slug' => 'zengarden-indoor-tabletop-water-fountain',
                'description' => 'Relaxing waterfall sound, LED lighted crystal ball, natural river rocks included.',
                'price' => 2499.00,
                'stock' => 35,
                'sku' => 'SKU-HOME-013',
                'image_url' => 'https://images.unsplash.com/photo-1507473885765-e6ed057f782c?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'ErgoRest Aluminum Foldable Laptop Stand',
                'slug' => 'ergorest-aluminum-foldable-laptop-stand',
                'description' => '6-level height adjustment, hollow heat dissipation design, portable velvet pouch.',
                'price' => 1199.00,
                'stock' => 110,
                'sku' => 'SKU-HOME-014',
                'image_url' => 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'EcoPure Airtight Glass Food Containers Set',
                'slug' => 'ecopure-airtight-glass-food-containers-set',
                'description' => 'High borosilicate glass, BPA-free snap locking lids, microwave and oven safe.',
                'price' => 2299.00,
                'stock' => 50,
                'sku' => 'SKU-HOME-015',
                'image_url' => 'https://images.unsplash.com/photo-1615865417491-9556867d5cc1?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'Lumina Outdoor Solar Motion Lights 4-Pack',
                'slug' => 'lumina-outdoor-solar-motion-lights-4pack',
                'description' => 'IP65 waterproof garden security lights with 120-degree motion sensor.',
                'price' => 1899.00,
                'stock' => 70,
                'sku' => 'SKU-HOME-016',
                'image_url' => 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'ChefCraft 6-Piece Stainless Steel Knife Block',
                'slug' => 'chefcraft-6piece-stainless-steel-knife-block',
                'description' => 'Precision sharp chef knife, bread knife, santoku knife and wooden storage block.',
                'price' => 3499.00,
                'stock' => 40,
                'sku' => 'SKU-HOME-017',
                'image_url' => 'https://images.unsplash.com/photo-1593618998160-e34014e67546?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'ComfortFoam Orthopedic Neck Bed Pillow',
                'slug' => 'comfortfoam-orthopedic-neck-bed-pillow',
                'description' => 'Contoured ergonomic cervical memory foam pillow with breathable washable cover.',
                'price' => 2199.00,
                'stock' => 65,
                'sku' => 'SKU-HOME-018',
                'image_url' => 'https://images.unsplash.com/photo-1584100936595-c0654b55a2e2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'AromaFresh Electric Coffee Bean Grinder',
                'slug' => 'aromafresh-electric-coffee-bean-grinder',
                'description' => 'Stainless steel blades, 150W motor, push button control for coffee, spices, nuts.',
                'price' => 1799.00,
                'stock' => 80,
                'sku' => 'SKU-HOME-019',
                'image_url' => 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'home-lifestyle',
                'name' => 'SmartScale Bluetooth Body Fat Digital Scale',
                'slug' => 'smartscale-bluetooth-body-fat-digital-scale',
                'description' => '13 body composition metrics including BMI, muscle mass, visceral fat, synced to app.',
                'price' => 1699.00,
                'stock' => 90,
                'sku' => 'SKU-HOME-020',
                'image_url' => 'https://images.unsplash.com/photo-1576678927484-cc909957088c?auto=format&fit=crop&w=800&q=80',
            ],

            // PREMIUM FOOTWEAR (20 Products)
            [
                'category_slug' => 'footwear',
                'name' => 'Minimalist Leather Minimal Sneaker',
                'slug' => 'minimalist-leather-minimal-sneaker',
                'description' => 'Handcrafted full-grain Italian leather upper, durable rubber cupsole, cushioned antimicrobial footbed.',
                'price' => 6499.00,
                'stock' => 40,
                'sku' => 'SKU-FOOT-001',
                'image_url' => 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'ApexRunner Lightweight Breathable Running Shoes',
                'slug' => 'apexrunner-lightweight-running-shoes',
                'description' => 'Engineered knit mesh upper, responsive foam midsole cushion, high traction rubber outsole.',
                'price' => 3999.00,
                'stock' => 60,
                'sku' => 'SKU-FOOT-002',
                'image_url' => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'Heritage Formal Leather Oxford Shoes',
                'slug' => 'heritage-formal-leather-oxford-shoes',
                'description' => 'Genuine calfskin leather, Goodyear welt construction, memory foam padded insoles.',
                'price' => 5499.00,
                'stock' => 35,
                'sku' => 'SKU-FOOT-003',
                'image_url' => 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'TrekMaster Waterproof Outdoor Hiking Boots',
                'slug' => 'trekmaster-waterproof-hiking-boots',
                'description' => 'Waterproof membrane lining, ankle support collar, Vibram lug grip sole for rough trails.',
                'price' => 7499.00,
                'stock' => 25,
                'sku' => 'SKU-FOOT-004',
                'image_url' => 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'UrbanSlip Canvas Casual Slip-On Shoes',
                'slug' => 'urbanslip-canvas-casual-slipon-shoes',
                'description' => 'Durable washed canvas fabric, elastic side goring for easy on and off, vulcanized sole.',
                'price' => 1899.00,
                'stock' => 85,
                'sku' => 'SKU-FOOT-005',
                'image_url' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'SpeedCourt Professional Indoor Sports Shoes',
                'slug' => 'speedcourt-professional-indoor-sports-shoes',
                'description' => 'Non-marking natural gum rubber sole, lateral stability wings for badminton and squash.',
                'price' => 4299.00,
                'stock' => 45,
                'sku' => 'SKU-FOOT-006',
                'image_url' => 'https://images.unsplash.com/photo-1608231387042-66d1773070a5?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'Classic Chelsea Suede Ankle Boots',
                'slug' => 'classic-chelsea-suede-ankle-boots',
                'description' => 'Premium genuine suede leather, elastic side panels, back pull tab, stacked heel.',
                'price' => 5999.00,
                'stock' => 30,
                'sku' => 'SKU-FOOT-007',
                'image_url' => 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'CloudStride Max Cushion Daily Trainers',
                'slug' => 'cloudstride-max-cushion-daily-trainers',
                'description' => 'Thick shock absorbing nitrogen infused foam, seamless upper mesh for long walking.',
                'price' => 4799.00,
                'stock' => 50,
                'sku' => 'SKU-FOOT-008',
                'image_url' => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'CourtPro Retro Leather Basketball Sneakers',
                'slug' => 'courtpro-retro-leather-basketball-sneakers',
                'description' => 'Mid-top ankle support collar, padded tongue, retro colorblocked leather panels.',
                'price' => 5299.00,
                'stock' => 40,
                'sku' => 'SKU-FOOT-009',
                'image_url' => 'https://images.unsplash.com/photo-1552346154-21d32810aba3?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'LuxeLoafer Penny Leather Dress Loafers',
                'slug' => 'luxeloafer-penny-leather-dress-loafers',
                'description' => 'Hand-stitched leather upper, moc toe design, flexible rubber driver outsole.',
                'price' => 4499.00,
                'stock' => 35,
                'sku' => 'SKU-FOOT-010',
                'image_url' => 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'TrailBlazer All-Terrain Trail Running Shoes',
                'slug' => 'trailblazer-allterrain-trail-running-shoes',
                'description' => 'Rock protection plate, aggressive multi-directional lugs, quick lace system.',
                'price' => 4999.00,
                'stock' => 45,
                'sku' => 'SKU-FOOT-011',
                'image_url' => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'BreezeSlide Ergonomic EVA Foam Slides',
                'slug' => 'breezeslide-ergonomic-eva-foam-slides',
                'description' => '1.5-inch thick cloud slide sole, waterproof quick drying EVA material.',
                'price' => 1299.00,
                'stock' => 100,
                'sku' => 'SKU-FOOT-012',
                'image_url' => 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'Formal Double Monk Strap Leather Shoes',
                'slug' => 'formal-double-monk-strap-leather-shoes',
                'description' => 'Burnished toe cap, dual brass buckles, premium full-grain leather upper.',
                'price' => 5799.00,
                'stock' => 30,
                'sku' => 'SKU-FOOT-013',
                'image_url' => 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'AeroKnit Sock Style Slip-On Sneakers',
                'slug' => 'aeroknit-sock-style-slipon-sneakers',
                'description' => '3D stretch sock upper, ultra lightweight air cushion heel unit.',
                'price' => 3299.00,
                'stock' => 60,
                'sku' => 'SKU-FOOT-014',
                'image_url' => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'RuggedTrek Steel Toe Safety Work Boots',
                'slug' => 'ruggedtrek-steel-toe-safety-work-boots',
                'description' => 'ASTM certified steel toe, oil and slip resistant heavy duty rubber sole.',
                'price' => 6299.00,
                'stock' => 25,
                'sku' => 'SKU-FOOT-015',
                'image_url' => 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'FlexFit Breathable Gym Workout Shoes',
                'slug' => 'flexfit-breathable-gym-workout-shoes',
                'description' => 'Flat heel stability base for deadlifts and squat training, flexible forefoot mesh.',
                'price' => 3699.00,
                'stock' => 55,
                'sku' => 'SKU-FOOT-016',
                'image_url' => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'Casual Suede Moccasin Driving Shoes',
                'slug' => 'casual-suede-moccasin-driving-shoes',
                'description' => 'Grip rubber pebble sole extension, hand stitched toe seam, soft suede finish.',
                'price' => 3899.00,
                'stock' => 40,
                'sku' => 'SKU-FOOT-017',
                'image_url' => 'https://images.unsplash.com/photo-1614252235316-8c857d38b5f4?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'HighTop Vintage Canvas Sneakers',
                'slug' => 'hightop-vintage-canvas-sneakers',
                'description' => 'High top ankle coverage, classic star rubber patch, durable canvas upper.',
                'price' => 2299.00,
                'stock' => 75,
                'sku' => 'SKU-FOOT-018',
                'image_url' => 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'HydroPro Waterproof Outdoor Rain Boots',
                'slug' => 'hydropro-waterproof-outdoor-rain-boots',
                'description' => '100% waterproof vulcanized rubber construction, removable cushioned inner sole.',
                'price' => 2799.00,
                'stock' => 35,
                'sku' => 'SKU-FOOT-019',
                'image_url' => 'https://images.unsplash.com/photo-1520639888713-7851133b1ed0?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'footwear',
                'name' => 'CloudSoft Orthotic Support Sandals',
                'slug' => 'cloudsoft-orthotic-support-sandals',
                'description' => 'Anatomical arch support footbed, adjustable hook and loop synthetic leather straps.',
                'price' => 2499.00,
                'stock' => 60,
                'sku' => 'SKU-FOOT-020',
                'image_url' => 'https://images.unsplash.com/photo-1603808033192-082d6919d3e1?auto=format&fit=crop&w=800&q=80',
            ],

            // BEAUTY & WELLNESS (20 Products)
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'RadiantGlow Vitamin C Face Serum 30ml',
                'slug' => 'radiantglow-vitamin-c-face-serum-30ml',
                'description' => '20% L-Ascorbic Acid with Ferulic Acid and Vitamin E for skin brightening and collagen booster.',
                'price' => 1299.00,
                'stock' => 100,
                'sku' => 'SKU-BEAU-001',
                'image_url' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'HydroBoost Hyaluronic Moisturizing Cream',
                'slug' => 'hydroboost-hyaluronic-moisturizing-cream',
                'description' => 'Non-comedogenic gel moisturizer providing 72-hour continuous hydration.',
                'price' => 1499.00,
                'stock' => 85,
                'sku' => 'SKU-BEAU-002',
                'image_url' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'SonicClean Waterproof Facial Scrub Device',
                'slug' => 'sonicclean-waterproof-facial-scrub-device',
                'description' => 'Ultra-hygienic silicone sonic pulsations cleanses pores and removes 99.5% dirt.',
                'price' => 2499.00,
                'stock' => 50,
                'sku' => 'SKU-BEAU-003',
                'image_url' => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'SilkSoft Keratin Hair Repair Oil 100ml',
                'slug' => 'silksoft-keratin-hair-repair-oil-100ml',
                'description' => 'Pure Argan and Macadamia nut oil serum tames frizz and restores shine to damaged hair.',
                'price' => 999.00,
                'stock' => 110,
                'sku' => 'SKU-BEAU-004',
                'image_url' => 'https://images.unsplash.com/photo-1608248597262-8382d6880ef2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'ProTrimmer Cordless Hair & Beard Groomer',
                'slug' => 'protrimmer-cordless-hair-beard-groomer',
                'description' => 'Self-sharpening titanium T-blade, 120-minute battery runtime, 4 guide combs.',
                'price' => 2199.00,
                'stock' => 75,
                'sku' => 'SKU-BEAU-005',
                'image_url' => 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'VelvetSkin Activated Charcoal Detox Mask',
                'slug' => 'velvetskin-activated-charcoal-detox-mask',
                'description' => 'Deep pore purifying peel-off face mask enriched with tea tree extract.',
                'price' => 799.00,
                'stock' => 130,
                'sku' => 'SKU-BEAU-006',
                'image_url' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'PureOrganics Cold-Pressed Argan Body Oil',
                'slug' => 'pureorganics-coldpressed-argan-body-oil',
                'description' => '100% organic Moroccan argan oil for deep skin nourishment and cuticle care.',
                'price' => 1199.00,
                'stock' => 90,
                'sku' => 'SKU-BEAU-007',
                'image_url' => 'https://images.unsplash.com/photo-1608248597262-8382d6880ef2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'ThermalGlow Ceramic Hair Straightener Brush',
                'slug' => 'thermalglow-ceramic-hair-straightener-brush',
                'description' => 'Anti-scald ionic heating brush, 30-second rapid heat up, adjustable temp settings.',
                'price' => 2799.00,
                'stock' => 40,
                'sku' => 'SKU-BEAU-008',
                'image_url' => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'SpaCare Ultrasonic Skin Spatula Scrubber',
                'slug' => 'spacare-ultrasonic-skin-spatula-scrubber',
                'description' => 'High frequency vibrations remove blackheads, dead skin, and enhances serum absorption.',
                'price' => 1999.00,
                'stock' => 60,
                'sku' => 'SKU-BEAU-009',
                'image_url' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'AquaHydrate Invisible Sunscreen Gel SPF 50',
                'slug' => 'aquahydrate-invisible-sunscreen-gel-spf50',
                'description' => 'PA++++ broad spectrum UVA/UVB protection, zero white cast, water resistant formula.',
                'price' => 899.00,
                'stock' => 140,
                'sku' => 'SKU-BEAU-010',
                'image_url' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'HerbalNourish Sulfate-Free Anti-Dandruff Shampoo',
                'slug' => 'herbalnourish-sulfatefree-antidandruff-shampoo',
                'description' => 'Infused with tea tree, rosemary oil and salicylic acid for scalp soothing.',
                'price' => 749.00,
                'stock' => 110,
                'sku' => 'SKU-BEAU-011',
                'image_url' => 'https://images.unsplash.com/photo-1608248597262-8382d6880ef2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'LuxeScents French Vanilla Eau De Parfum 100ml',
                'slug' => 'luxescents-french-vanilla-eau-de-parfum-100ml',
                'description' => 'Long-lasting luxury fragrance with notes of warm vanilla, amber, and sandalwood.',
                'price' => 3499.00,
                'stock' => 45,
                'sku' => 'SKU-BEAU-012',
                'image_url' => 'https://images.unsplash.com/photo-1592945403244-b3fbafd7f539?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'JadeRoller Natural Quartz Facial Massager',
                'slug' => 'jaderoller-natural-quartz-facial-massager',
                'description' => 'Dual-headed authentic rose quartz roller and Gua Sha tool for lymphatic drainage.',
                'price' => 1099.00,
                'stock' => 85,
                'sku' => 'SKU-BEAU-013',
                'image_url' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'MicroMist Nano Ionic Warm Facial Steamer',
                'slug' => 'micromist-nano-ionic-warm-facial-steamer',
                'description' => 'Opens up pores for deep cleansing, aromatherapy oil chamber tray included.',
                'price' => 2299.00,
                'stock' => 50,
                'sku' => 'SKU-BEAU-014',
                'image_url' => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'LipLuxe Tinted Berry Hydrating Lip Balm',
                'slug' => 'lipluxe-tinted-berry-hydrating-lip-balm',
                'description' => 'Shea butter and jojoba oil moisturizes dry lips with a natural rosy tint.',
                'price' => 499.00,
                'stock' => 160,
                'sku' => 'SKU-BEAU-015',
                'image_url' => 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'ProGroom Waterproof Electric Nose Trimmer',
                'slug' => 'progroom-waterproof-electric-nose-trimmer',
                'description' => 'Dual-edge rotary blades, washable stainless steel head, battery powered.',
                'price' => 899.00,
                'stock' => 100,
                'sku' => 'SKU-BEAU-016',
                'image_url' => 'https://images.unsplash.com/photo-1621607512214-68297480165e?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'DeadSea Exfoliating Salt Body Scrub 350g',
                'slug' => 'deadsea-exfoliating-salt-body-scrub-350g',
                'description' => 'Enriched with sweet almond oil and sea minerals for smooth glowing skin.',
                'price' => 1299.00,
                'stock' => 70,
                'sku' => 'SKU-BEAU-017',
                'image_url' => 'https://images.unsplash.com/photo-1556228720-195a672e8a03?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'NightRepair 0.5% Retinol Anti-Aging Cream',
                'slug' => 'nightrepair-05-retinol-antiaging-cream',
                'description' => 'Formulated with peptide complex and niacinamide to reduce fine lines and wrinkles.',
                'price' => 1899.00,
                'stock' => 60,
                'sku' => 'SKU-BEAU-018',
                'image_url' => 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'ProStylist Ion Professional Hair Dryer',
                'slug' => 'prostylist-ion-professional-hair-dryer',
                'description' => '2000W AC motor, negative ionic tech reduces frizz, magnetic concentrator nozzle.',
                'price' => 3299.00,
                'stock' => 45,
                'sku' => 'SKU-BEAU-019',
                'image_url' => 'https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'beauty-wellness',
                'name' => 'Botanical Essential Oils Gift Set 6-Pack',
                'slug' => 'botanical-essential-oils-gift-set-6pack',
                'description' => '100% pure lavender, tea tree, eucalyptus, lemongrass, peppermint, orange oils.',
                'price' => 1499.00,
                'stock' => 80,
                'sku' => 'SKU-BEAU-020',
                'image_url' => 'https://images.unsplash.com/photo-1608248597262-8382d6880ef2?auto=format&fit=crop&w=800&q=80',
            ],

            // SPORTS & FITNESS (20 Products)
            [
                'category_slug' => 'sports-fitness',
                'name' => 'PowerGrip Adjustable Dumbbell Set 20kg',
                'slug' => 'powergrip-adjustable-dumbbell-set-20kg',
                'description' => 'Quick turn weight dial adjustment from 2.5kg to 20kg with anti-slip knurled grip handle.',
                'price' => 11999.00,
                'stock' => 30,
                'sku' => 'SKU-SPOR-001',
                'image_url' => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'EcoFlex Extra Thick 8mm Yoga Mat',
                'slug' => 'ecoflex-extra-thick-8mm-yoga-mat',
                'description' => 'Eco-friendly TPE material with alignment lines and shoulder carrying strap included.',
                'price' => 1699.00,
                'stock' => 85,
                'sku' => 'SKU-SPOR-002',
                'image_url' => 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'SpeedCount Digital Jump Rope with Counter',
                'slug' => 'speedcount-digital-jump-rope-counter',
                'description' => 'Tangle-free steel wire cable, weight tracking memory LCD screen, weighted handles.',
                'price' => 999.00,
                'stock' => 110,
                'sku' => 'SKU-SPOR-003',
                'image_url' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'PowerBand Heavy Resistance Loop Bands 5-Pack',
                'slug' => 'powerband-heavy-resistance-loop-bands-5pack',
                'description' => '100% natural latex elastic workout bands with carrying pouch and exercise guide.',
                'price' => 1199.00,
                'stock' => 120,
                'sku' => 'SKU-SPOR-004',
                'image_url' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'ProPull Wall-Mounted Heavy Duty Pull Up Bar',
                'slug' => 'propull-wallmounted-heavy-duty-pullup-bar',
                'description' => 'Multi-grip positions, 200kg capacity solid steel frame with mounting hardware.',
                'price' => 2999.00,
                'stock' => 40,
                'sku' => 'SKU-SPOR-005',
                'image_url' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'HydroFlask 1L Stainless Steel Sports Bottle',
                'slug' => 'hydroflask-1l-stainless-steel-sports-bottle',
                'description' => 'BPA-free vacuum insulated leak-proof bottle with straw lid and silicone boot.',
                'price' => 1499.00,
                'stock' => 95,
                'sku' => 'SKU-SPOR-006',
                'image_url' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'CoreRoller Ergonomic Ab Roller Wheel',
                'slug' => 'coreroller-ergonomic-ab-roller-wheel',
                'description' => 'Ultra-wide wheel base for maximum stability, includes knee pad mat.',
                'price' => 1299.00,
                'stock' => 70,
                'sku' => 'SKU-SPOR-007',
                'image_url' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'MuscleRelief Percussion Deep Tissue Massage Gun',
                'slug' => 'musclerelief-percussion-deep-tissue-massage-gun',
                'description' => '30 speed levels, 6 interchangeable massage heads, quiet brushless motor.',
                'price' => 4999.00,
                'stock' => 45,
                'sku' => 'SKU-SPOR-008',
                'image_url' => 'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'FlexGrip Padded Weightlifting Gym Gloves',
                'slug' => 'flexgrip-padded-weightlifting-gym-gloves',
                'description' => 'Integrated wrist wrap support, breathable mesh back, anti-slip silicone palm.',
                'price' => 899.00,
                'stock' => 130,
                'sku' => 'SKU-SPOR-009',
                'image_url' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'ActivePace GPS Sports Watch with Heart Rate',
                'slug' => 'activepace-gps-sports-watch-heart-rate',
                'description' => 'Dedicated running modes, VO2 max estimation, 50m water resistance.',
                'price' => 9999.00,
                'stock' => 35,
                'sku' => 'SKU-SPOR-010',
                'image_url' => 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'PowerRack Squat & Bench Press Stand',
                'slug' => 'powerrack-squat-bench-press-stand',
                'description' => 'Adjustable height bar safety catches, 250kg weight limit for home gym workouts.',
                'price' => 14999.00,
                'stock' => 15,
                'sku' => 'SKU-SPOR-011',
                'image_url' => 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'SpeedAgility Footwork Training Ladder 6m',
                'slug' => 'speedagility-footwork-training-ladder-6m',
                'description' => '12 adjustable flat rungs, 6 agility cones and carrying bag included.',
                'price' => 1199.00,
                'stock' => 80,
                'sku' => 'SKU-SPOR-012',
                'image_url' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'SlamBall Heavy Duty Medicine Ball 8kg',
                'slug' => 'slamball-heavy-duty-medicine-ball-8kg',
                'description' => 'No-bounce textured rubber shell filled with sand for functional strength training.',
                'price' => 2499.00,
                'stock' => 50,
                'sku' => 'SKU-SPOR-013',
                'image_url' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'FoamRelease High Density Muscle Massage Roller',
                'slug' => 'foamrelease-high-density-muscle-massage-roller',
                'description' => 'Grid trigger point texture for myofascial release and post-workout recovery.',
                'price' => 1399.00,
                'stock' => 90,
                'sku' => 'SKU-SPOR-014',
                'image_url' => 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'ProPunch Heavy Duty Boxing Punching Bag 4ft',
                'slug' => 'propunch-heavy-duty-boxing-punching-bag-4ft',
                'description' => 'Synthetic leather shell, reinforced hanging chains, swivel hook included.',
                'price' => 3999.00,
                'stock' => 25,
                'sku' => 'SKU-SPOR-015',
                'image_url' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'ActiveBelt Running Hydration Waist Pack',
                'slug' => 'activebelt-running-hydration-waist-pack',
                'description' => 'Water resistant phone pouch with 2 BPA-free 250ml water bottles included.',
                'price' => 1299.00,
                'stock' => 75,
                'sku' => 'SKU-SPOR-016',
                'image_url' => 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'FlexStretch Leg Extension Strap Band',
                'slug' => 'flexstretch-leg-extension-strap-band',
                'description' => 'Multi-loop neoprene stretching strap for ballet, yoga, and hamstring flexibility.',
                'price' => 799.00,
                'stock' => 100,
                'sku' => 'SKU-SPOR-017',
                'image_url' => 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'PowerWrist Adjustable Ankle Weights 2kg Pair',
                'slug' => 'powerwrist-adjustable-ankle-weights-2kg-pair',
                'description' => 'Breathable neoprene fabric with strong Velcro straps for walking or leg workouts.',
                'price' => 1499.00,
                'stock' => 85,
                'sku' => 'SKU-SPOR-018',
                'image_url' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'CoreBalance 65cm Anti-Burst Exercise Ball',
                'slug' => 'corebalance-65cm-antiburst-exercise-ball',
                'description' => 'Heavy duty PVC Swiss ball with quick inflation hand pump included.',
                'price' => 1399.00,
                'stock' => 70,
                'sku' => 'SKU-SPOR-019',
                'image_url' => 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'sports-fitness',
                'name' => 'FastGrip 2-Player Table Tennis Racket Set',
                'slug' => 'fastgrip-2player-table-tennis-racket-set',
                'description' => '7-ply wood blade rackets with ITTF approved rubber padding, 3 balls and case.',
                'price' => 1899.00,
                'stock' => 60,
                'sku' => 'SKU-SPOR-020',
                'image_url' => 'https://images.unsplash.com/photo-1517838277536-f5f99be501cd?auto=format&fit=crop&w=800&q=80',
            ],

            // TOYS & HOBBIES (20 Products)
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'RoboTech STEM Programmable Robot Kit',
                'slug' => 'robotech-stem-programmable-robot-kit',
                'description' => 'Scratch & Python coding compatible robot vehicle with obstacle avoidance sensors.',
                'price' => 4999.00,
                'stock' => 40,
                'sku' => 'SKU-TOYS-001',
                'image_url' => 'https://images.unsplash.com/photo-1485827404703-89b55fcc595e?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'MasterMind 1000-Piece Landscape Jigsaw Puzzle',
                'slug' => 'mastermind-1000piece-landscape-jigsaw-puzzle',
                'description' => 'Premium recycled cardboard with anti-glare linen finish and reference poster.',
                'price' => 999.00,
                'stock' => 100,
                'sku' => 'SKU-TOYS-002',
                'image_url' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'SpeedRacer 1:16 High-Speed RC Monster Truck',
                'slug' => 'speedracer-116-highspeed-rc-monster-truck',
                'description' => '36 km/h top speed, 2.4GHz remote control, 4WD suspension dampers.',
                'price' => 3499.00,
                'stock' => 50,
                'sku' => 'SKU-TOYS-003',
                'image_url' => 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'CreativeMind Deluxe 80-Piece Acrylic Painting Set',
                'slug' => 'creativemind-deluxe-80piece-acrylic-painting-set',
                'description' => 'Includes desktop wooden easel, stretched canvases, acrylic tubes, brushes and palette.',
                'price' => 2799.00,
                'stock' => 45,
                'sku' => 'SKU-TOYS-004',
                'image_url' => 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'AstroView Refractor Astronomy Telescope 70mm',
                'slug' => 'astroview-refractor-astronomy-telescope-70mm',
                'description' => 'Fully coated glass optics, adjustable stainless steel tripod and smartphone adapter.',
                'price' => 7999.00,
                'stock' => 25,
                'sku' => 'SKU-TOYS-005',
                'image_url' => 'https://images.unsplash.com/photo-1516339901601-2e1b62dc0c45?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'Classic Handcrafted Wooden Chess Board Set',
                'slug' => 'classic-handcrafted-wooden-chess-board-set',
                'description' => 'Folding magnetic rosewood board with felted bottom Staunton chess pieces.',
                'price' => 2199.00,
                'stock' => 65,
                'sku' => 'SKU-TOYS-006',
                'image_url' => 'https://images.unsplash.com/photo-1529699211952-734e80c4d42b?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'CinePic Instant Print Digital Camera for Kids',
                'slug' => 'cinepic-instant-print-digital-camera-kids',
                'description' => 'Zero-ink thermal paper print, 1080P HD video recording, fun photo frames and games.',
                'price' => 3999.00,
                'stock' => 35,
                'sku' => 'SKU-TOYS-007',
                'image_url' => 'https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'MagicBrick Architectural City Building Blocks 1200pcs',
                'slug' => 'magicbrick-architectural-city-building-blocks',
                'description' => 'Compatible with major building block brands, detailed instruction manual included.',
                'price' => 3299.00,
                'stock' => 40,
                'sku' => 'SKU-TOYS-008',
                'image_url' => 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'PolyDice D&D Polyhedral RPG Dice Set 7-Piece',
                'slug' => 'polydice-dnd-polyhedral-rpg-dice-set-7piece',
                'description' => 'Heavy sharp-edged resin dice with gold ink numbering and leather drawstring pouch.',
                'price' => 899.00,
                'stock' => 150,
                'sku' => 'SKU-TOYS-009',
                'image_url' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'AeroFly Flying Orb Boomerang Spinner Toy',
                'slug' => 'aerofly-flying-orb-boomerang-spinner-toy',
                'description' => '360-degree rotating LED light ball, boomerang return flight mode, USB rechargeable.',
                'price' => 1299.00,
                'stock' => 90,
                'sku' => 'SKU-TOYS-010',
                'image_url' => 'https://images.unsplash.com/photo-1594787318286-3d835c1d207f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'SketchPro 72-Piece Artist Colored Pencil Tin',
                'slug' => 'sketchpro-72piece-artist-colored-pencil-tin',
                'description' => 'Soft core break resistant lead for smooth blending and shading artwork.',
                'price' => 1899.00,
                'stock' => 70,
                'sku' => 'SKU-TOYS-011',
                'image_url' => 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'PlayDough Deluxe Non-Toxic Modeling Clay Kit',
                'slug' => 'playdough-deluxe-nontoxic-modeling-clay-kit',
                'description' => '24 vivid clay colors with extrusion tools, cutters, rolling pin and storage box.',
                'price' => 999.00,
                'stock' => 110,
                'sku' => 'SKU-TOYS-012',
                'image_url' => 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'SoundMaster 37-Key Electronic Toy Piano',
                'slug' => 'soundmaster-37key-electronic-toy-piano',
                'description' => 'Built-in microphone, 8 instrument sounds, rhythm tempos and recording function.',
                'price' => 2499.00,
                'stock' => 45,
                'sku' => 'SKU-TOYS-013',
                'image_url' => 'https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'DinoDig Science Archaeology Fossil Excavation Kit',
                'slug' => 'dinodig-science-archaeology-excavation-kit',
                'description' => 'Dig out 12 genuine dinosaur fossils using real chisel tools and magnifying glass.',
                'price' => 1499.00,
                'stock' => 80,
                'sku' => 'SKU-TOYS-014',
                'image_url' => 'https://images.unsplash.com/photo-1587654780291-39c9404d746b?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'QuadRacer Mini Indoor Pocket RC Drone',
                'slug' => 'quadracer-mini-indoor-pocket-rc-drone',
                'description' => 'Altitude hold, 360-degree flip mode, headless mode for beginners, protective guards.',
                'price' => 1999.00,
                'stock' => 65,
                'sku' => 'SKU-TOYS-015',
                'image_url' => 'https://images.unsplash.com/photo-1508614589041-895b88991e3e?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'StoryBook Classic Illustrated Children Box Set',
                'slug' => 'storybook-classic-illustrated-children-boxset',
                'description' => 'Hardcover collection of 10 timeless illustrated fairy tales and moral stories.',
                'price' => 1799.00,
                'stock' => 60,
                'sku' => 'SKU-TOYS-016',
                'image_url' => 'https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'PixelArt Magnetic Drawing Board Game',
                'slug' => 'pixelart-magnetic-drawing-board-game',
                'description' => 'Mess-free magnetic bead art board with stylus and 20 pattern cards.',
                'price' => 1199.00,
                'stock' => 95,
                'sku' => 'SKU-TOYS-017',
                'image_url' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'AquaCanvas Extra Large Water Doodle Mat',
                'slug' => 'aquacanvas-extra-large-water-doodle-mat',
                'description' => '100x80cm reusable water drawing mat with 4 magic water pens and stencils.',
                'price' => 1399.00,
                'stock' => 85,
                'sku' => 'SKU-TOYS-018',
                'image_url' => 'https://images.unsplash.com/photo-1513364776144-60967b0f800f?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'MasterCraft 3D Wooden DIY Galleon Ship Kit',
                'slug' => 'mastercraft-3d-wooden-diy-galleon-ship-kit',
                'description' => 'Laser cut wooden puzzle pieces assemble into a detailed antique sailing ship.',
                'price' => 2199.00,
                'stock' => 50,
                'sku' => 'SKU-TOYS-019',
                'image_url' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
            ],
            [
                'category_slug' => 'toys-hobbies',
                'name' => 'SpeedCube 3x3 Magnetic High-Speed Cube',
                'slug' => 'speedcube-3x3-magnetic-highspeed-cube',
                'description' => 'Stickerless competition speed cube with adjustable spring tension system.',
                'price' => 799.00,
                'stock' => 140,
                'sku' => 'SKU-TOYS-020',
                'image_url' => 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?auto=format&fit=crop&w=800&q=80',
            ],
        ];

        foreach ($productsData as $prodData) {
            $catSlug = $prodData['category_slug'];
            $imgUrl = $prodData['image_url'];
            unset($prodData['category_slug'], $prodData['image_url']);

            $product = Product::updateOrCreate(
                ['slug' => $prodData['slug']],
                array_merge($prodData, ['category_id' => $categories[$catSlug]->id])
            );

            ProductImage::updateOrCreate(
                ['product_id' => $product->id],
                [
                    'image' => $imgUrl,
                ]
            );
        }
    }
}
